language: ruby
before_install:
  - gem update --system
  - gem install bundler
  - bundle --version
rvm:
  - 2.3.0
  - 2.3.3
  - 2.4.0
  - 2.4.3
  - 2.5.0
  - 2.5.4
  - 2.6.0
  - 2.6.1
  - jruby-9.1.7.0
