module TTFunk
  class Table
    module Common
      autoload :AlternateSet,                  'ttfunk/table/common/alternate_set'
      autoload :ChainRuleTable,                'ttfunk/table/common/chain_rule_table'
      autoload :ChainSubClassRuleTable,        'ttfunk/table/common/chain_sub_class_rule_table'
      autoload :ChainSubClassSet,              'ttfunk/table/common/chain_sub_class_set'
      autoload :ChainSubRuleSet,               'ttfunk/table/common/chain_sub_rule_set'
      autoload :ClassDef,                      'ttfunk/table/common/class_def'
      autoload :ClassDef1,                     'ttfunk/table/common/class_def1'
      autoload :ClassDef2,                     'ttfunk/table/common/class_def2'
      autoload :ClassRangeTable,               'ttfunk/table/common/class_def2'
      autoload :ConditionSet,                  'ttfunk/table/common/condition_set'
      autoload :ConditionTable,                'ttfunk/table/common/condition_table'
      autoload :CoverageTable,                 'ttfunk/table/common/coverage_table'
      autoload :CoverageTable1,                'ttfunk/table/common/coverage_table1'
      autoload :CoverageTable2,                'ttfunk/table/common/coverage_table2'
      autoload :FeatureList,                   'ttfunk/table/common/feature_list'
      autoload :FeatureTable,                  'ttfunk/table/common/feature_table'
      autoload :FeatureTableSubstitutionList,  'ttfunk/table/common/feature_table_substitution_list'
      autoload :FeatureTableSubstitutionTable, 'ttfunk/table/common/feature_table_substitution_table'
      autoload :FeatureVariationList,          'ttfunk/table/common/feature_variation_list'
      autoload :FeatureVariationTable,         'ttfunk/table/common/feature_variation_table'
      autoload :LangSysTable,                  'ttfunk/table/common/lang_sys_table'
      autoload :LigatureSet,                   'ttfunk/table/common/ligature_set'
      autoload :LigatureTable,                 'ttfunk/table/common/ligature_table'
      autoload :LookupList,                    'ttfunk/table/common/lookup_list'
      autoload :LookupTable,                   'ttfunk/table/common/lookup_table'
      autoload :RangeTable,                    'ttfunk/table/common/range_table'
      autoload :ScriptList,                    'ttfunk/table/common/script_list'
      autoload :ScriptTable,                   'ttfunk/table/common/script_table'
      autoload :SequenceTable,                 'ttfunk/table/common/sequence_table'
      autoload :SubClassRule,                  'ttfunk/table/common/sub_class_rule'
      autoload :SubClassSet,                   'ttfunk/table/common/sub_class_set'
      autoload :SubRule,                       'ttfunk/table/common/sub_rule'
      autoload :SubRuleSet,                    'ttfunk/table/common/sub_rule_set'
      autoload :Subst,                         'ttfunk/table/common/subst'
      autoload :SubstLookupTable,              'ttfunk/table/common/subst_lookup_table'
    end
  end
end
